export const movies= [
    {   id: 1,
        title: "The Avengers",
        plot: "Super heros movie",
        price: 199,
        rating: 8.9,
        stars: 0,
        fav: false,
        isIncart: false,
        poster: "https://m.media-amazon.com/images/I/71niXI3lxlL._SY879_.jpg"
    },
    {   id: 2,
        title: "The Dark Knight",
        plot: "Batman faces the Joker, who brings chaos to Gotham City.",
        price: 249,
        rating: 9.0,
        stars: 0,
        fav: false,
        isIncart: false,
        poster: "https://m.media-amazon.com/images/I/61RxB8tSkrL.jpg"
    },
    {   id: 3,
        title: "Iron Man",
        plot: "A billionaire industrialist and genius inventor, Tony Stark, is kidnapped and forced to build a devastating weapon.",
        price: 199,
        rating: 8.5,
        stars: 0,
        fav: false,
        isIncart: false,
        poster: "https://m.media-amazon.com/images/I/51CDHXxg46L._SX300_SY300_QL70_FMwebp_.jpg"
    },
    {   id: 4,
        title: "Spider-Man: Homecoming",
        plot: "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man.",
        price: 229,
        rating: 7.4,
        stars: 0,
        fav: false,
        isIncart: false,
        poster: "https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg"
    },
    {   id: 5,
        title: "Black Panther",
        plot: "T'Challa returns home to the African nation of Wakanda to take his rightful place as king.",
        price: 299,
        rating: 7.3,
        stars: 0,
        fav: false,
        isIncart: false,
        poster: "https://lumiere-a.akamaihd.net/v1/images/p_blackpanther_19754_4ac13f07.jpeg"
    },
    {   id: 6,
        title: "Wonder Woman",
        plot: "Diana, princess of the Amazons, trained to be an unconquerable warrior.",
        price: 199,
        rating: 7.9,
        stars: 0,
        fav: false,
        isIncart: false,
        poster: "https://m.media-amazon.com/images/I/717t+mNlLeL._AC_SY879_.jpg"
    } 
]  